import { Lato, Playfair } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const lato = Lato({
  weight: "400",
  variable: "--lato",
  subsets: ["latin"],
});

const playfair = Playfair({
  variable: "--playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "Decore AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="lato min-h-full flex flex-col">

        <Navbar></Navbar>

        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
